#!/usr/bin/env bash

# Plot JSON formatted cryptor portfolio valuation history on stdin using gnuplot(1).
# Consumes a portfilio valuation history generated by `cryptor` e.g.
#
#   cryptor history -portfolio personal | examples/plot-history.sh
#
# Makes use of the `jq(1)` command and the accompanying `history.gnuplot` gnuplot script.

set -u -e -o pipefail
tmpfile="$(mktemp)"
cat - | jq -r "group_by(.date) | map(. | map(select(.cost > 0)) | sort_by(.time) | last) | .[] | select(.) | [.name, .date, .cost, .value, (.value-.cost)/.cost*100] | @csv" > "$tmpfile"
plotscript="$(dirname "$(readlink -e "$0")")/history.gnuplot"
gnuplot -p -e "data='$tmpfile'" "$plotscript"
rm "$tmpfile"
