#!/bin/bash

# Plot JSON formatted cryptor portfolio valuation on stdin using gnuplot(1).
# Consumes a portfilio valuation generated by `cryptor` e.g.
#
#   cryptor valuate -format json -portfolio personal | examples/plot-valuation.sh
#
# Makes use of the `jq(1)` command and the accompanying `valuation.gnuplot` gnuplot script.

set -u -e -o pipefail
tmpfile="$(mktemp)"
cat - | jq -r '.[] | . as $p | .assets[] | [$p.name, $p.date, .symbol, .allocation] | @csv' > "$tmpfile"
cat "$tmpfile"
plotscript="$(dirname "$(readlink -e "$0")")/valuation.gnuplot"
gnuplot -p -e "data='$tmpfile'" "$plotscript"
rm "$tmpfile"