#!/bin/bash

# Plot JSON formatted cryptor portfolio valuation history on stdin using gnuplot(1).
# Consumes a portfilio valuation history generated by `cryptor` e.g.
#
#   cryptor history -format json -portfolio personal | examples/plot-history.sh
#
# Accepts optional chart title as first script argument e.g.
#
#   cryptor history -format json -portfolio personal | examples/plot-history.sh "Personal Portfolio"
#
# Makes use of the `jq(1)` command and the accompanying `history.gnuplot` gnuplot script.

set -u -e -o pipefail
tmpfile="$(mktemp)"
if [ $# -gt 0 ]; then
    title="$1"
else
    title="Portfolio Valuation History"
fi
cat - | jq -r '.[] | [.name, .date, .usdcost, .value] | @csv' > "$tmpfile"
cat "$tmpfile"
plotscript="$(dirname "$(readlink -e "$0")")/history.gnuplot"
gnuplot -p -e "data='$tmpfile'; title='$title'" "$plotscript"
rm "$tmpfile"